### ISSUE TITLE
Undefined index: secretMode

### ISSUE THREAD

**Issue by devillD** [YehudaEi/FilesServerManagment#1]
Undefined index: secretMode in SysManager.php.php on line 267

**Comment by YehudaEi** [comment]
Hi,
What version of PHP are you using?

**Comment by devillD** [comment]
sir, it's 7.1

**Comment by YehudaEi** [comment]
Sorry for the late response, I fixed it now.

**Comment by devillD** [comment]
thanks a lot sir
